### ISSUE TITLE
Hourly timestep

### ISSUE THREAD

**Issue by KevisPachos** [pywr/pywr#1014]
Hi @jetuk,

I am modelling a water-energy system that requires me to use an hourly timestep for generation and storage of solar energy. Therefore, my Excel input file for energy demand, has an hourly time-step that looks like:

01/01/2025  00:00:00
01/01/2025  01:00:00
01/01/2025  02:00:00
etc

I tried to set my timestepper to `"timestep": "D"`  but got the following index error:
```
IndexError: Failed to identify frequency of dataset "../../../hourly-demand-data/energy-demand-hourly.xlsx"
```
Is it possible to use an hourly timestep in pywr? 

Thanks,
Kevis

**Comment by jetuk** [comment]
I think I would say this is not fully supported, but may work. The core timestep is defined as a float number of days. You would have to set the `"timestep": "H"` for hourly. There will be some caveats to this with some of the parameters possibly written under the assumption that the timestep is an integer number of days. However, the core timestepping at hourly frequency *should* work because that's what pywr-dcopf (https://github.com/pywr/pywr-dcopf see examples/tests) uses.

The error you have above is less to do with the timestep and something to do with Pandas not knowing the data frequency. Are you sure they are no duplicates or missing entries in the index? I.e. can you get this as a "H" frequency index outside of Pywr with just Pandas?

**Comment by KevisPachos** [comment]
Thank you @jetuk, indeed there was an error with my index. I have fixed that and it solved with an hourly time-step.
