### ISSUE TITLE
Energy generation according a downstream water level section.

### ISSUE THREAD

**Issue by wdvichete84** [pywr/pywr#1038]
Hello.
I've been trying to include a water level node downstream of a turbine node to use the h (off the power generation) according the difference of the storage elevation and the downstream section water elevation. I try to not change the source code (cython files) using the water elevation node and change the turbine elevation, which not allow to use a string in this field. 

Do you think is possible to allow the turbine elevation changing for each time step to get the h = storage elevation - downstream section elevation ? (without change the original source). This downstream elevation seems relative important to small hydropower's (run of the river). 
(TypeError: must be real number, not str)

Follow attached the files (discharges, .json and .ipynb)
Thanks in advance.
[model_data.zip](https://github.com/pywr/pywr/files/7856524/model_data.zip)
.

**Comment by jetuk** [comment]
Hi @wdvichete84 

Apologies for not replying sooner. 

Instead of modifying the code you could add a parameter for the turbine's elevation and another one for the downstream elevation (but negative), and then use an `AggregatedParameter` to sum them together. This will give you the difference between the two and you can use it in the hydropower calculations. Hopefully that make can help.

I'm afraid I have not had time to look at your model in detail. I'll try to find some time over the next week or so.

**Comment by wdvichete84** [comment]
Hi @jetuk 

I appreciate your reply. 
I will try as you recommended.

Thanks a lot!

**Comment by jetuk** [comment]
@wdvichete84 did this work for you? Can I close this issue?

**Comment by wdvichete84** [comment]
@jetuk my apologies to not reply you sooner.

Your recommendation to use an AggregatedParameter worked.  However, in this case the turbine elevation should be at 0 m elevation (as I'm using elevation levels in reservoir and downstream section).

Thanks a lot.
Attached the model is working with the downstream water level into the energy generation.
[model_data_rev1.zip](https://github.com/pywr/pywr/files/8207122/model_data_rev1.zip)
