### ISSUE TITLE
Balancing storages in pywr

### ISSUE THREAD

**Issue by ahamilton144** [pywr/pywr#1058]
Hi there, I am trying to figure out if it is possible to balance releases across nodes such that the relative storages are held equal across nodes. For example, consider two reservoirs A and B, with stochastic inflows, which are jointly responsible for meeting deliveries to demand node C. I would like to keep the storage fractions (A/Amax) and (B/Bmax) roughly equal throughout the simulation. If I simply set the costs for each reservoir to be constant and equal, then the LP will select one of the reservoirs and drain it all the way down to meet demand C, before drawing at all from reservoir B. I also tried adding a dynamic cost parameter that depends on each reservoir's current storage fraction, which helps, but it results in oscillatory behavior where each reservoir is relied on fully for one or two days, until its reservoir drops low enough for the LP to switch to the other reservoir, which is then relied on fully. Ideally I'd prefer to have the daily releases split between the reservoir to provide smoother and more balanced releases. 

There are two ways I can think of implementing this. The first is to use an aggregated node with the "factors" set using dynamic parameters based on the current storage levels. The documentation says this is not yet supported, but then I saw that there might be some support for node.aggregated_with_dynamic_factors in cython_glpk.pyx. Can you please provide more information on whether this is supported? If so, is there any documentation of how to use it? If not, are there currently any plans to add it? 

The other option would be to alter the LP problem by adding constraints based on dynamic parameters:
      (A - X_A)/Amax - (B - X_B)/Bmax < eps
                     AND
      (A - X_A)/Amax - (B - X_B)/Bmax > -eps
where X_A and X_B are the flows out of reservoirs A and B in the current time step (i.e., the decision variables), and epsilon is the allowable difference in storage fraction (e.g., 0.05). Again there is some language in cython_glpk.pyx that makes me think this might be supported, but I'm not really sure. If so, can you provide any information on how I might implement it?

I hope this is all clear. Thank you very much for any guidance you can provide! 
Andrew

**Comment by jetuk** [comment]
Andrew,

Apologies for the slow reply I have been on summer holidays.

> The first is to use an aggregated node with the "factors" set using dynamic parameters based on the current storage levels

This is an interesting idea that I haven't thought of trying before. It should be supported since v1.9.0.

> The documentation says this is not yet supported

Can you tell me where it says this, because it should be supported now and this documentation needs to be corrected. I think the only real example of usage at the moment are the two tests [here](https://github.com/pywr/pywr/blob/3d1a0915dccf315fff9e7af35b9a3fb0dcbd38dd/tests/test_agg_constraints.py#L336).

> The other option would be to alter the LP problem ...

Can you point me at the part of `cython_glpk.pyx` you are looking at? I'm not sure there is currently a constraint that links two storage nodes like your example. 

Generally, this is a known problem in the simple way Pywr's LP and penalty cost model works. In practice is often not as bad as the theoretical example because of differing inflows, network constraints, etc. Or if it is so simple you can argue to just merge the two storage nodes in Pywr (or add an `AggregatedStorage` node) and look at behaviour of the combined volume. 

Another approach, that I haven't had time to work on, is to implement the equivalent of `PiecewiseLink` for storage nodes (i.e. `PiecewiseStorage`). In this model each "chunk" of storage could have its own cost in the LP. Therefore, you could make it use the chunks in all nodes before moving to the lower ones. 

You might be able to trial this by splitting your two nodes into two pairs. Where it gets a bit weird is if the target volume is changing through the year. This implies the `max_volume` of each chunk is changing. Pywr should support this, but there might be some gremlins.

Alternatively, the other approach is to implement a true non-linear cost function on the storage nodes. However, this is not supported in GLPK. It is something I want to design into the next major revision of Pywr though. However, I'm not sure what impact it will have on runtimes.

**Comment by ahamilton144** [comment]
Hi James, 

No problem, thanks for the info! I'm actually working on a third alternative, which is to dynamically set max flow parameters on outflow links based on the preferred ratio, along with secondary higher-cost links to use in cases where the ratio can't be satisfied. I think this is probably a bit safer compared to aggregated node factors since it isn't a binding constraint.

But good to know that the aggregated node factors can be a parameter in case I run into issues with this solution. The documentation I was referring to is this paragraph in ``Cookbook/Aggregated nodes/Constraining flow using a ratio``: "Note that the aggregated node “D” is not connected to any nodes via an edge. The constraint is applied regardless. The factors must also remain a constant throughout a simulation (i.e. they can not be Parameter definitions references). This limitation could be resolved in a future version of Pywr."

Thanks,
Andrew

**Comment by jetuk** [comment]
Documentation change in #1060.
