### ISSUE TITLE
Read parameter value for InterpolatedVolumeParameter

### ISSUE THREAD

**Issue by ALMurgatroyd** [pywr/pywr#1137]
Hi all, similar query to #926:

Is it possible amend InterpolatedVolumeParameter to read a volume value from another parameter? The current setting only permits input from a 'values', 'url' or 'table' entry.

In the example below I'm trying to use the interpolated volume parameter to interpolate between the parameters: 'myparam1' and 'myparam2'.

Thanks in advance :)

Example code:

    "flowparam": {...},
    "myparam1": {...},
    "myparam2": {...},
    "flow": {
        "type": "indexedarray",
        "index_parameter": "resource_state",
        "params": [
            "flowparam",
            {
                "type": "interpolatedvolume",
                "node": "Storage",
                "volumes": [
                    "myparam1",
                    "myparam2"
                ],
                "values": [
                    {
                        "type": "constant",
                        "value": 0
                    },
                    "flowparam"
                ],
                "interp_kwargs": {
                    "kind": "linear"
                }
            },
            {
                "type": "constant",
                "values": 0
            }
        ]
    }

**Comment by jetuk** [comment]
I don't think this is supported at the moment. That's partly because the interpolated parameters setup an `interp1d` object at the beginning that is then used for different values of volume (i.e. it can't change over time).

However, `ControlCurveInterpolatedParameter` might be able to do this for you if you just want linear interpolation. There you use the "parameters" key instead of "values".

**Comment by ALMurgatroyd** [comment]
Thanks @jetuk - ControlCurveInterpolatedParameter has done the job!
