### ISSUE TITLE
Standardise approach to Genetic Algorithms (GA)

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#16]
Example of using a GA to generate a reservoir control curve:

https://github.com/snorfalorpagus/pywr/blob/ga/examples/example_ga1.py

Investigate adding some standard structures for this kind of thing:
- [ ] Reservoir control curves
- [ ] Individual parameters

**Comment by jetuk** [comment]
I propose we do this in a `pywr.optimisation`  package. 

I currently have a separate project / repo to do interaction with Borg, but it is not the only MOEA solution. The interaction between `Parameters` and `Recorders` should be agnostic to the MOEA being used and therefore can be implemented in the main `pywr` repository. 

I envisage the same type of approach as with the LP solvers. We provide a generic way to provide multiple MOEA solvers using the same set of core objects.

I will keep the Borg solver outside of MOEA because of the licence problem, but we can add one for say [inspyred](http://aarongarrett.github.io/inspyred/) in the main repo.

**Comment by snorfalorpagus** [comment]
```
class BorgModel(Model):
    """
    Extension to the pywr.core.Model to add features for using Borg MOEA.
    """
    def __init__(self, *args, **kwargs):
        super(BorgModel, self).__init__(*args, **kwargs)
        self.problem = None
        # Container for BorgVariable objects
        self.variables = []
        self._variable_map = None
        # Container for BorgObjective objects
        self.objectives = []

    def setup(self, ):
        """
        Setup the model and Borg problem before solving.
        """
        super(BorgModel, self).setup()
        # Create index map from variable array to BorgVariable objects
        variable_map = [0]
        for var in self.variables:
            variable_map.append(var.size)

        # Create the BorgProblem object with correct number of variables
        print(variable_map[-1], len(self.objectives))
        self.problem = PywrProblem(self, variable_map[-1], len(self.objectives), 0)

        # Apply bounds
        for i, var in enumerate(self.variables):
            var.set_bounds(variable_map[i])

        for i, obj in enumerate(self.objectives):
            obj.set_epsilon(i)

        self._variable_map = variable_map

    def evaluate(self, vars, objs, cons):
        """
        Evalute the current variables
        """
        # Update BorgVariable objects with new values
        for i, j, var in zip(self._variable_map[:-1], self._variable_map[1:], self.variables):
            var.update(vars[i:j])
```
Note: BORG is not GPL-compatible.

I think we can integrate two parts of this into the vanilla pywr code:

* A `Parameter.update` / `Parameter.set_value` to update the values on a Parameter passed from *somewhere*.
* A mapping function to apply the parameters. I was thinking something like ```[(1, desal_max_flow), (12, reservoir_control_curve)]```

**Comment by jetuk** [comment]
Can we close this?

**Comment by snorfalorpagus** [comment]
Yes.
