### ISSUE TITLE
RiverSplit node is not implemented in the new framework

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#41]
The way that rivers are represented in the model has changed significantly, and the old `RiverSplit` node is no longer functional.

Now that the distinction between a "supply" network and "river" network no longer exists (they are both just networks with flows), conceptually the old `RiverSplit` and `Blender` are the same thing. They can be implemented in the new framework as a compound node, with a single child input and N child outputs (why limit to 2?). The complexity is in how we add the constraint to the LP to ensure the balance between flows via the different routes from the outputs is fixed; presumably we need to add some code to the solver(s) to handle this.

Currently there are some tests for `RiverSplit` marked as failures. These should be updated.

**Comment by jetuk** [comment]
Yes I thought about this as well. You are correct it requires an additional
constraint so the solvers need to be aware. I guess that means it's some
sort 'core' node type?

**Comment by snorfalorpagus** [comment]
Yes, I think that makes it a core type. I want to make sure we're not overlooking anything. Are there any other nodes/concepts we've identified that will require modification to the solver? Should the solver be extendable with some sort of plugin/hooks? I think probably not, as speed for WR models is the main objective here, but wanted to float the idea.

**Comment by jetuk** [comment]
I agree to probably not make the solvers extendable. They could advertise which features/nodes they support? And therefore exit gracefully if an unsupported node type is found. With just two solvers implemented, and not a huge number of node types, it is probably desirable to have them both support everything.

The only other concept missing is `Group` licences. I haven't done anything with these, and I don't know if it can be abstracted away from the solver like the per node licences. The `Group` code was in the original solver implementation, but I removed it.

The following tests are marked to fail because they contain RiverSplit
- `test_run_river2` in `test_run.py`
- `test_run_mrf` in `test_run.py`
- `test_slots_from` in `test_core.py`

**Comment by snorfalorpagus** [comment]
I've started work on this in https://github.com/snorfalorpagus/pywr/tree/ratio

**Comment by snorfalorpagus** [comment]
See #71

**Comment by snorfalorpagus** [comment]
Closed by #174 and #180.
