### ISSUE TITLE
Support for some commercial solvers

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#557]
Is this possible with the GPL? How would it be a achieved. Examples that have been put  forward,

- Gurobi
- CPLEX

**Comment by snorfalorpagus** [comment]
I think the answer is no. Although it's complicated and there hasn't been a test case for it AFAIK. The GPL says that if you link, statically or dynamically, then you've created a derivative product and if released then both must be made available under the GPL. Obviously we can't do that as we don't have the source / permission for CPLEX etc.

**Comment by jetuk** [comment]
Pyomo can do this because it uses the BSD licence?

**Comment by jetuk** [comment]
CGAL has a quadratic solver and is GPL.

https://doc.cgal.org/latest/QP_solver/index.html#Chapter_Linear_and_Quadratic_Programming_Solver

**Comment by jetuk** [comment]
Could someone write a non-GPL `Solver` subclass and distribute it themselves? Or does the mere fact you have to do `from pywr.solvers import Solver` bring in the GPL?

**Comment by snorfalorpagus** [comment]
I think you're not allowed to release code that doesn't work without the GPL part.

For example, Pywr doesn't work without GLPK (if we ignore lpsolve for the moment). Even though we're not releasing the GLPK source/binary, because Pywr depends on GLPK, it must be released under a GPL licence.

Another example would be a plugin for QGIS. These have to be released as GPL, because the API they are written to use is GPL.

**Comment by jetuk** [comment]
Closing this for now.
