### ISSUE TITLE
Data consumption warning

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#562]
I've just come across a mistake in a model, where the incorrect date range was used:

```
model.timestepper.start = "1900-01-01"
model.timestepper.end = "1999-01-01"
```

Should have been:

```
model.timestepper.start = "1900-01-01"
model.timestepper.end = "1999-12-31"
```

This is something that the dataframe/tablesarray parameter could have spotted. Perhaps we could raise a warning if not all of the data is being consumed? The risk is that this becomes noise.

**Comment by jetuk** [comment]
The `DataFrameParameter` already has a check for a different length. 

https://github.com/pywr/pywr/blob/47ad8ddcd6a2f7355fd4be7c6eeb2dbb6de1b83f/pywr/parameters/_parameters.pyx#L183

The `align_and_resample_dataframe` already slices to the required timesteps of the model after resampling. The warning needs to be in this function rather than the parameter itself.
