### ISSUE TITLE
Put licence a notice at the start of each source file

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#658]
As recommended by:

https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile

**Comment by snorfalorpagus** [comment]
I can't say I'm in favour of this suggestion. I don't think it adds any meaningful protection beyond just having a licence file in the repository. If someone is going to copy part of the code into another project who is to say they would also copy of licence at the top of the file? What's to stop them copying just a single function/class because they don't need the whole file? Why not put a copyright notice at the top of every function then? Whenever I see projects that actually do this (and they are few and far between, although GLPK is actually an example of one that does) it always comes across to me as "hey! did you know this is open source! isn't that great?" and a bit in-your-face.

**Comment by jetuk** [comment]
Linux does it! I don't have a strong opinion. I just saw the recommendation while reading some of the FAQ.
