### ISSUE TITLE
slots for parameters

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#829]
Yesterday @jetuk and I discussed the possible need for parameters to return multiple values (i.e the value returned should be able to vary based on which component is requesting it). This could be implemented similarly to how slots are for nodes

**Comment by snorfalorpagus** [comment]
What is the use case for this? It seems like it could add a lot of complexity.

**Comment by Batch21** [comment]
The context was a discussion around dynamic groundwater and shifting some of the calculations out of the LP into parameters, however I think we came up with a solution that avoids the need for this change by creating a custom node.

**Comment by jetuk** [comment]
In the general case this is where you have a parameter that implements some logic the results of which need to be applied in multiple places. For example:

- A calculation that needs to update both cost and max_flow of the same, or
- A calculation that needs to update the max_flow on multiple nodes.

Currently the only way to achieve this is using multiple parameters because each one can only provide one value to the model.

I agree it would be more complicated, but it might also make some models more "readable" with fewer shim parameters that just exposes different values.

**Comment by jetuk** [comment]
I think we agreed to not implement this one as it would be too complex and confusing.
