### ISSUE TITLE
Injected Population to Platypus

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#887]
Hi @jetuk 

I was looking at the `PywrRandomGenerator` class to see a way to inject a complete set of non-dominated solutions into `Platypus` to continue an algorithm search from the last non-dominated solutions I got from a previous search. However, I noticed that using this `pywr` class I can inject only one non-dominated solution (the solution there is in the Json file). I would like to ask you two questions:

1) Do you know if it is ok just inject one solution to continue the search? or I would need to inject a complete set of non-dominated solutions equal to the pop-size?
2) If you recommend me to inject the complete set of non-dominated solutions. Could you share some ideas about how this could be efficiently implemented in `pywr`? I could dedicate time to do this implementation but it would be helpful to get some tips from you.

Thanks

https://github.com/pywr/pywr/blob/e7b4e35c5eef08442e1f390c4a5b8270cb0ae926/pywr/optimisation/platypus.py#L135

**Comment by jetuk** [comment]
> Do you know if it is ok just inject one solution to continue the search? or I would need to inject a complete set of non-dominated solutions equal to the pop-size?

I think both are "ok", but obviously quite different starting points for the search. Injecting an entire population would make it start more like where it finished before.

> If you recommend me to inject the complete set of non-dominated solutions. Could you share some ideas about how this could be efficiently implemented in pywr? I could dedicate time to do this implementation but it would be helpful to get some tips from you.

I did think about this when writing the `PywrRandomGenerator`.  Another variation would be random perturbations of the JSON solution (rather than pure random between the variable bounds - which is what `RandomGenerator` does).

I think you could do this by providing an optional set of data to `PywrRandomGenerator`. This would contain the variable value information for however many solutions you have. However, one thing we do not currently have within Pywr is a defined format for saving/serialising a "solution". This is also something that we *could* standardise on, and support out of the box saving optimisation results in this format and then re-importing them for either restarting a search or running a model with a solution in place.

@Batch21 @matrosoe tagging you both for opinion; particularly on the last sentence above. Should Pywr support some sort of solution serialisation/deserialisation format?

Finally, one thing to think about is that not all algorithms would consume all the solutions you provide (i.e. depending on the size of the initial population). From a `PywrRandomGenerator`'s point of view it just gets asked to provide a solution an unknown number of times. So it may not provide all solutions if Platypus doesn't ask for them. And would also have to provide additional (random)  solutions if Platypus asks for me than you have (the current implementation does this by deferring back to `RandomGenerator` after providing the first solution).

**Comment by jetuk** [comment]
@Jmiguel17 please see #892 for some functionality around this.
